version: '3.8'
services: 
    front:
        build: 
            context: .
            dockerfile: Dockerfile
        command: sh -c "yarn install && yarn serve"
        ports: 
            - '8080:8080'
        volumes: 
            - '.:/app'
        stdin_open: true